
[MobsHandling]
	#Controls Spawn Chance For Creeper
	"Creeper Spawn Chance" = 8.0
	#Controls Spawn Chance For Zombie
	"Zombie Spawn Chance" = 8.0
	#Controls Spawn Chance For Wither
	"Wither Spawn Chance" = 8.0
	#Controls Spawn Chance For TnT
	"TNT Spawn Chance" = 8.0
	#Controls Illusioner Spawn Chances
	"Illusioner Spawn Chance" = 8.0
	#All The Remaining Mods Rate
	"Remaing Spawn Rate" = 8.0

["Pot Settings"]
	#The Chance of spawning pot every two minutes
	PotChance = 6.0

